DROP TABLE SPECTATOR;
DROP TABLE PLIANT;
DROP TABLE RECENZIE;
DROP TABLE EVENIMENT;
DROP TABLE BILET;
DROP TABLE ORGANIZATOR;
DROP TABLE VOLUNTAR;
DROP TABLE EVENIMENT_ORGANIZATOR;
DROP TABLE VOLUNTAR_EVENIMENT;

CREATE TABLE SPECTATOR (
    ID_SPECTATOR NUMBER PRIMARY KEY,
    NUME VARCHAR2(222),
    VARSTA NUMBER,
    TELEFON VARCHAR2(22)
);

INSERT INTO SPECTATOR VALUES(101, 'ANDREI POPA', 22, '+40712345678');

SELECT * FROM SPECTATOR;

CREATE TABLE PLIANT (
    ID_PLIANT NUMBER PRIMARY KEY,
    ID_SPECTATOR NUMBER,
    DENUMIRE VARCHAR2(222),
    PUBLIC_TINTA VARCHAR2(222),
    FOREIGN KEY (ID_SPECTATOR) REFERENCES SPECTATOR(ID_SPECTATOR)
);

CREATE TABLE RECENZIE (
    ID_RECENZIE NUMBER PRIMARY KEY,
    ID_SPECTATOR NUMBER,
    NUMAR_STELE NUMBER,
    MESAJ VARCHAR2(222),
    FOREIGN KEY (ID_SPECTATOR) REFERENCES SPECTATOR(ID_SPECTATOR)
);

CREATE TABLE EVENIMENT (
    ID_EVENIMENT NUMBER PRIMARY KEY,
    DENUMIRE VARCHAR2(222),
    LOCATIE VARCHAR2(222),
    DATA_ORA DATE
);

CREATE TABLE BILET (
    ID_BILET NUMBER PRIMARY KEY,
    ID_SPECTATOR NUMBER,
    ID_EVENIMENT NUMBER,
    PRET VARCHAR2(222),
    VIP VARCHAR2(222),
    FOREIGN KEY (ID_SPECTATOR) REFERENCES SPECTATOR(ID_SPECTATOR),
    FOREIGN KEY (ID_EVENIMENT) REFERENCES EVENIMENT(ID_EVENIMENT)
);

CREATE TABLE ORGANIZATOR (
    ID_ORGANIZATOR NUMBER PRIMARY KEY,
    NUME VARCHAR2(222),
    AN_DEBUT VARCHAR2(222)
);

CREATE TABLE VOLUNTAR (
    ID_VOLUNTAR NUMBER PRIMARY KEY,
    NUME VARCHAR2(222),
    EXPERIENTA VARCHAR2(222)
);

CREATE TABLE EVENIMENT_ORGANIZATOR (
    ID_EVENIMENT NUMBER,
    ID_ORGANIZATOR NUMBER,
    PRIMARY KEY (ID_EVENIMENT, ID_ORGANIZATOR),
    FOREIGN KEY (ID_EVENIMENT) REFERENCES EVENIMENT(ID_EVENIMENT),
    FOREIGN KEY (ID_ORGANIZATOR) REFERENCES ORGANIZATOR(ID_ORGANIZATOR)
);

CREATE TABLE VOLUNTAR_EVENIMENT (
    ID_VOLUNTAR NUMBER,
    ID_EVENIMENT NUMBER,
    PRIMARY KEY (ID_VOLUNTAR, ID_EVENIMENT),
    FOREIGN KEY (ID_VOLUNTAR) REFERENCES VOLUNTAR(ID_VOLUNTAR),
    FOREIGN KEY (ID_EVENIMENT) REFERENCES EVENIMENT(ID_EVENIMENT)
);
